# version: "3"
# services:
#   angular-app:
#     image: angular-app
#     ports:
#       - "9090:9090"
#     networks:
#       - product-management-system
#   product-frontend:
#     image: product-frontend-app
#     ports:
#       - "80:80"
#     depends_on:
#       - product-backend
#     networks:
#       - product-management-system
# networks:
#   product-management-system: